

logging:
  level:
    org.springframework.web: ERROR
    com.mallorcatrens.pricecomparer: TRACE

---

spring:
  profiles: local
server:
  port: 80

    
---

spring:
  profiles: Pruebas
server:
  port: 80    